// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZeUX1GJEbNdsC4r1ax-8iorKD2PBL00',
    appId: '1:449405528552:web:9f0f5ab64687a19c961c5d',
    messagingSenderId: '449405528552',
    projectId: 'flutternotification-fd902',
    authDomain: 'flutternotification-fd902.firebaseapp.com',
    storageBucket: 'flutternotification-fd902.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7aHYo90kufIrOSqA4FKK4MmkiGDWhxgs',
    appId: '1:449405528552:android:317d5af34dc36c47961c5d',
    messagingSenderId: '449405528552',
    projectId: 'flutternotification-fd902',
    storageBucket: 'flutternotification-fd902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFOzsyDXtjtRQgYahWQJ5THirDy8n-9HQ',
    appId: '1:449405528552:ios:4286de5afbc27ca0961c5d',
    messagingSenderId: '449405528552',
    projectId: 'flutternotification-fd902',
    storageBucket: 'flutternotification-fd902.appspot.com',
    iosBundleId: 'com.example.flutterNotificationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFOzsyDXtjtRQgYahWQJ5THirDy8n-9HQ',
    appId: '1:449405528552:ios:966415cbe678ca99961c5d',
    messagingSenderId: '449405528552',
    projectId: 'flutternotification-fd902',
    storageBucket: 'flutternotification-fd902.appspot.com',
    iosBundleId: 'com.example.flutterNotificationExample.RunnerTests',
  );
}
